### ISSUE TITLE
[Feature request] - Ability to acutally open the character from the char manager

### ISSUE THREAD

**Issue by The-Istar** [sakhavhyand/SillyTavern-AnotherCharManager#23]
Thanks for this plugin, it looks awesome. Finally it gives me the ability to actually see characters without tags.
However, sometimes I would like to actually open a character to properly edit the advanced sittings or even just talk with it.
Would it be possible to add the ability to actually open the character directly from the Char management screen?

**Comment by sakhavhyand** [comment]
Hi! Thanks for the feedback, I'm gradually adding most of the edit menu to the extension so access the advanced settings should comes at a moment.
I'm gonna look at this and also gonna look to add a button to open the chat too.
No ETA since I will also surely try to enhance the UI, which one of theses two features you would want to see first ?

**Comment by The-Istar** [comment]
Thanks for the reply.
I guess a button to open the character and chat would be great as this would then immediately allow me to edit the character fully.
Though very happy to see you are still developing the extension.

As an idea for future features as well, if you are interested: 
- Add the ability to update characters from Chub if there are newer releases on chub.
- Add the ability to import tags for existing characters from chub.
- Improve tag management. Currently there is no way to easily merge tags and corresponding characters. This is made worse by the fact that SillyTavern is case sensitive. For example: Girl and girl are 2 different tags in Sillytavern and there is no easy way to merge there into 1 tag without editing every character card manually.

Just some ideas if you are interested.

**Comment by sakhavhyand** [comment]
Hey, sorry for the late answer.
To answer your last question:

- Update characters from Chub is not an easy task, I've look at it by curiosity and the way the Chub API works is not really made to do this easily. I may still have a deeper look at it later
- There is actually ways to import tags from Chub like this one :https://github.com/city-unit/st-auto-tagger.
- To merge tags, since the last version of ST (or the previous one, I don't remember), if you delete a tag in the global tag list, it will ask you if you want to attribute an existing tag to the character that add the deleted one.

And for your initial demand, I'm gonna push an update today or tomorrow (need some testing and code check) that will add a button to access the Advanced Definitions menu and another one to close my windows and open the original character edition panel of ST.
